#pragma once

#define UI_COLOR_BLACK Color(0x000000FF)
#define UI_COLOR_WHITE Color(0xFFFFFFFF)
#define UI_COLOR_RED Color(0xFF0000FF)
#define UI_COLOR_GREEN Color(0x00FF00FF)
#define UI_COLOR_BLUE Color(0x0000FFFF)
#define UI_COLOR_YELLOW Color(0xFFFF00FF)
#define UI_COLOR_CYAN Color(0x00FFFFFF)
#define UI_COLOR_MAGENTA Color(0xFF00FFFF)
