name: Educore Workflow
on: [push]
jobs:
  MakePkg-Msbuild:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7
      - name: checkout
        run: |
          git submodule init
          git submodule update --remote
          git lfs install
          git lfs pull
      - name: build
        run: |
          python3 build.py build -release
          mkdir package
          copy bin\educore.exe package
          move assets package
          cd package
          tar -acf ../educore-windows.zip *
          cd ..
      - name: get version
        id: version
        run: |
          "version="+(Get-Content -Path .\docs\version).Trim() >> $env:GITHUB_ENV
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}.${{ steps.short-sha.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./educore-windows.zip
          asset_name: educore-windows.zip
          asset_content_type: application/zip
