name: EduTool Workflow
on: [push]
jobs:
  MakePkg-Msbuild:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        run: |
          git submodule init
          git submodule update --remote
      - name: build
        uses: ilammy/msvc-dev-cmd@v1
        run: |
          python3 build.py build
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}