name: Educore Weekly Build

on:
 schedule:
 - cron: "0 0 * * 1"
 workflow_dispatch

jobs:
  emscripten_compile:
    environment: "ske's secrets"
    runs-on: ubuntu-latest
    steps:
      - name: Set up emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize submodules/LFS
        run: |
          git submodule init
          git submodule update --remote
          git lfs install
          git lfs pull
      - name: Build with emscripten
        run: |
          chmod +x ./scripts/build-wasm.sh
          ./scripts/build-wasm.sh
          mv bin/wasm-out/* .
      - name: Copy artifacts to the server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "index.html,index.wasm,index.js,index.data"
          target: "/home/ubuntu/dat/ci/educore"
