name: Educore Weekly Build

on: [push]
  # schedule:
  # - cron: "0 0 * * 1"

jobs:
  emscripten_compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize submodules/LFS
        run: |
          git submodule init
          git submodule update --remote
          git lfs install
          git lfs pull
      - name: Build with emscripten
        run: |
          ./scripts/build-wasm.sh

