name: Educore Weekly Build

on: [push]
# schedule:
# - cron: "0 0 * * 1"

jobs:
  emscripten_compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize submodules/LFS
        run: |
          git submodule init
          git submodule update --remote
          git lfs install
          git lfs pull
      - name: Build with emscripten
        run: |
          chmod +x ./scripts/build-wasm.sh
          ./scripts/build-wasm.sh
      - name: Copy artifacts to the server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./bin/wasm-out/*
          target: /home/ubuntu/dat/ci/educore
